### ISSUE TITLE
build error in window

### ISSUE THREAD

**Issue by huangsusan** [smistad/FAST#123] opened 2019-11-04 04:16 UTC
Hello:
when I build in win,there is an error
error  C2664	“void std::_Ptr_base<_Ty>::_Reset0(_Ty (*),std::_Ref_count_base *)”: can not change “uchar *”to“unsigned char (*)[]”
error occured in FAST memory.cpp line 695

**Comment by smistad** [comment] 2019-11-04 09:04
There is no memory.cpp in FAST. I think you are using an old visual studio compiler that doesn't support C++14. Try and download visual studio 2017 community edition (free) and use that instead.

**Comment by huangsusan** [comment] 2019-11-04 13:14
it occoured in \Microsoft Visual Studio 14.0\VC\include\memory

**Comment by smistad** [comment] 2019-11-07 09:13
I believe I found the cause of your error, I have pushed a fix for it to master: https://github.com/smistad/FAST/commit/5a8e8af622c805c70c56c7c11d7a248ba8496e13
You could checkout this commit and try it

**Comment by huangsusan** [comment] 2019-11-07 09:19
Thank you,I will tyr it soon.

**Closed** 2019-11-08 13:23 UTC
